---
title: "Data Import"
author: "Anthéa von Borowski, Mengjiao Li, Leonie Demsar"
date: "2024-12-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())
```

## Ressources

### Libraries

```{r lib, message=F}
#install.packages("sf")
#install.packages("dplyr")
#install.packages("ggplot2")
#install.packages("readr")
#install.packages("tidyverse")
#install.packages("Hmisc")
#install.packages("car")
#install.packages("here")
#install.packages("httr")
#install.packages("jsonlite")

library(sf)
library(dplyr)
library(ggplot2)
library(readr)
library(tidyverse)
library(Hmisc)
library(car)
library(httr)
library(jsonlite)
library(here)
library(factoextra)
library(FactoMineR)


```


### Raw Data

Zunächst werden die Daten mithilfe der Here-Library heruntergeladen.

```{r rawdata}

inc_zip<-read.csv(here("Data", "Raw", "us_income_zipcode.csv"))
zcta<-st_read(here("Data", "Raw", "ZCTA", "tl_2016_us_zcta510.shp"))
data_nyc<-read.csv(here("Data", "Raw", "baumnyc.csv"))
demog<-read.csv(here("Data", "Raw", "ethn_zip.csv"))
zbp<-fromJSON(here("Data", "Raw", "zbp.json"))
housing<-read.csv(here("Data", "Raw", "newyork_housingunits.csv"))

```


### Mapping of locations to ZCTA zip-codes

```{r mapping}

points_ny <- st_as_sf(data_nyc, coords = c("longitude_coordinate", "latitude_coordinate"), crs = 4326) #transponing lat, long to point object

zcta_ny<-zcta[zcta$ZCTA5CE10 %in% 6390:14905,] #ignore all ZCTAs which are not NY
zcta_ny <- st_transform(zcta_ny, st_crs(points_ny)) #harmonize CRS values
zcta_ny$surface<-st_area(zcta_ny)

data <- st_join(st_sf(geometry = points_ny), zcta_ny, join = st_within) #join datasets to match zcta to trees
required_columns<-c("common_name","scientific_name","city", "state", "geometry", "zipcode", "condition", "native", "greater_metro", "ZCTA5CE10") 

baumnyc<-data[, required_columns, drop = F]
baumnyc$park<-is.na(baumnyc$ZCTA5CE10)



count_tree<-table(baumnyc$ZCTA)
count_tree
```


### Processing Income Data

```{r inc}

inc_zip<-inc_zip[inc_zip$Year ==2015,]
inc_zip$ZCTA<-as.numeric(substring(inc_zip$Geographic.Area.Name, 6)) 

inc_zip_ny<-inc_zip[inc_zip$ZCTA %in% 6390:14905,]
baumnyc$mean_income <- inc_zip$Households.Median.Income..Dollars.[match(baumnyc$ZCTA5CE10, inc_zip$ZCTA)]


```

### Processing Ethnicities Data

```{r eth}

#categories: white non hispanic/latino, black non hispanic/latino, asian non hispanic/latino, hispanic/latino, other

demog$ZCTA<-as.numeric(substring(demog$NAME, 7))

demog_ny<-demog[-1,]
demog_ny<-demog[demog$ZCTA %in% 6390:14905,]

baumnyc$pop<-as.numeric(demog_ny$B03002_001E[match(baumnyc$ZCTA5CE10, demog_ny$ZCTA)])
baumnyc$eth_white_nonhisp<-as.numeric(demog_ny$B03002_003E[match(baumnyc$ZCTA5CE10, demog_ny$ZCTA)])*100/baumnyc$pop
baumnyc$eth_afroam_nonhisp<-as.numeric(demog_ny$B03002_004E[match(baumnyc$ZCTA5CE10, demog_ny$ZCTA)])*100/baumnyc$pop
baumnyc$eth_asian_nonhisp<-as.numeric(demog_ny$B03002_006E[match(baumnyc$ZCTA5CE10, demog_ny$ZCTA)])*100/baumnyc$pop
baumnyc$eth_hisp<-as.numeric(demog_ny$B03002_012E[match(baumnyc$ZCTA5CE10, demog_ny$ZCTA)])*100/baumnyc$pop
baumnyc$eth_other<-100-(baumnyc$eth_white_nonhisp+baumnyc$eth_afroam_nonhisp+baumnyc$eth_asian_nonhisp+baumnyc$eth_hisp)
baumnyc$count_tree<-count_tree[baumnyc$ZCTA5CE10]
baumnyc$count_tree[is.na(baumnyc$count_tree)]<-0
baumnyc$zcta_surface<-as.numeric(zcta_ny$surface[match(baumnyc$ZCTA5CE10, zcta_ny$ZCTA5CE10)])/1000000
baumnyc$pop_density<-baumnyc$pop/baumnyc$zcta_surface
baumnyc$tree_density<-baumnyc$count_tree/baumnyc$zcta_surface

coords<-st_coordinates(baumnyc$geometry)
baumnyc$lat<-coords[1,]
baumnyc$long<-coords[2,]
baumnyc$geometry<-NULL
rm(coords)

unique(baumnyc$scientific_name)
```


### Recoding and grouping of data

```{r group}


baumnyc$native<-car::recode(baumnyc$native, "'naturally_occurring'= 0; 'introduced'=1;'no_info'=NA")
baumnyc$condition<-car::recode(baumnyc$condition, "'poor'=-1; 'fair' = 0; 'good' = 1")


baumnyc_gp<-data.frame(ZCTA = unique(baumnyc$ZCTA5CE10))

baumnyc_gp<- baumnyc %>%
  group_by(ZCTA = ZCTA5CE10) %>%
  dplyr::summarize(mean_native = mean(native, na.rm=T),
                   mean_condition = mean(condition, na.rm = T),
                   mean_income = mean(mean_income))

baumnyc_gp$pop<-as.numeric(demog_ny$B03002_001E[match(baumnyc_gp$ZCTA, demog_ny$ZCTA)])
baumnyc_gp$eth_white_nonhisp<-as.numeric(demog_ny$B03002_003E[match(baumnyc_gp$ZCTA, demog_ny$ZCTA)])/baumnyc_gp$pop
baumnyc_gp$eth_afroam_nonhisp<-as.numeric(demog_ny$B03002_004E[match(baumnyc_gp$ZCTA, demog_ny$ZCTA)])/baumnyc_gp$pop
baumnyc_gp$eth_asian_nonhisp<-as.numeric(demog_ny$B03002_006E[match(baumnyc_gp$ZCTA, demog_ny$ZCTA)])/baumnyc_gp$pop
baumnyc_gp$eth_hisp<-as.numeric(demog_ny$B03002_012E[match(baumnyc_gp$ZCTA, demog_ny$ZCTA)])/baumnyc_gp$pop
baumnyc_gp$eth_other<-1-(baumnyc_gp$eth_white_nonhisp+baumnyc_gp$eth_afroam_nonhisp+baumnyc_gp$eth_asian_nonhisp+baumnyc_gp$eth_hisp)
baumnyc_gp$count_tree<-count_tree[as.character(baumnyc_gp$ZCTA)]
baumnyc_gp$count_tree[is.na(baumnyc_gp$count_tree)]<-0
baumnyc_gp$surface<-as.numeric(zcta_ny$surface[match(baumnyc_gp$ZCTA, zcta_ny$ZCTA5CE10)])/1000000
baumnyc_gp$geometry<-NULL

baumnyc_gp$pop_density<-baumnyc_gp$pop/baumnyc_gp$surface
baumnyc_gp$tree_density<-baumnyc_gp$count_tree/baumnyc_gp$surface
#baumnyc_gp<-baumnyc_gp[-is.na(baumnyc_gp$ZCTA),]

```

# Including business/ residential data

```{r zbp}

colnames(zbp)<-c("ESTAB", "PAYANN", "zipcode")
zbp<-as.data.frame(zbp[-1,])
label(housing)<-housing[1,]
housing<-housing[-1,]
housing$ZCTA<-as.numeric(substring(housing$NAME, 7))

baumnyc_gp$housing_ttl<-as.numeric(housing$S2504_C01_001E[match(baumnyc_gp$ZCTA, housing$ZCTA)])
baumnyc_gp$housing_own<-as.numeric(housing$S2504_C02_001E[match(baumnyc_gp$ZCTA, housing$ZCTA)])
baumnyc_gp$housing_rent<-as.numeric(housing$S2504_C03_001E[match(baumnyc_gp$ZCTA, housing$ZCTA)])
baumnyc_gp$housing_own_pct<-baumnyc_gp$housing_own*100/baumnyc_gp$housing_ttl
baumnyc_gp$housing_density<-baumnyc_gp$housing_ttl/baumnyc_gp$surface
baumnyc_gp$housing_pop<-baumnyc_gp$housing_ttl/baumnyc_gp$pop
baumnyc_gp$ESTAB<-as.numeric(zbp$ESTAB[match(baumnyc_gp$ZCTA, zbp$zipcode)])
baumnyc_gp$ESTAB_density<-baumnyc_gp$ESTAB/baumnyc_gp$surface
baumnyc_gp$ESTAB_pop<-baumnyc_gp$ESTAB/baumnyc_gp$pop
baumnyc_gp$ESTAB_housing<-baumnyc_gp$ESTAB*100/baumnyc_gp$housing_ttl
baumnyc_gp$PAYANN<-as.numeric(zbp$PAYANN[match(baumnyc_gp$ZCTA, zbp$zipcode)])
baumnyc_gp$PAYANN_density<-baumnyc_gp$PAYANN/baumnyc_gp$surface
baumnyc_gp$PAYANN_pop<-baumnyc_gp$PAYANN/baumnyc_gp$pop

baumnyc_gp<-baumnyc_gp[!is.na(baumnyc_gp$ZCTA),]
``` 

### Classification business / residential

```{r class_norm}
set.seed(123) # For reproductibility

busres<-data.frame(ZCTA = baumnyc_gp$ZCTA, ESTAB_housing = baumnyc_gp$ESTAB_housing, PAYANN_density = baumnyc_gp$PAYANN_density, ESTAB_density = baumnyc_gp$ESTAB_density, housing_density = baumnyc_gp$housing_density)
rownames(busres)<-as.character(busres$ZCTA)
busres$ZCTA<-NULL
busres<-scale(busres)
```

### Writing data to CSV

```{r csv}

write.csv(baumnyc, here("Data", "Refined", "baumnyc2.csv"))
write.csv(baumnyc_gp, here("Data", "Refined", "baumnyc_gp2.csv"))

colnames(zbp)<-zbp[1,]
zbp<-zbp[-1,]

```