---
title: "DS_Project"
author: "Anthéa von Borowski, Mengjiao li, Leonie Demsar"
date: "2024-12-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ressources

### Libraries

```{r lib, message=F}
#install.packages("dplyr")
#install.packages("ggplot2")
#install.packages("readr")
#install.packages("olsrr")
#install.packages("lmtest")
#install.packages("moments")
install.packages("here")
install.packages("Rtools")
library(dplyr)
library(ggplot2)
library(readr)
library(lmtest)
library(olsrr)
library(moments)
library(here)
```

### Data Import

Data has been previously selected and modified in "data_import.Rmd".

```{r dataimport}

baumnyc<-read.csv(here("Data", "Refined", "baumnyc2.csv"))
baumnyc_gp<-read.csv(here("Data", "Refined", "baumnyc_gp2.csv"))

baumnyc$X<-NULL
baumnyc_gp$X<-NULL
```


### Multi-lineare Regression

#### Bäumedensität

H1.1 - Viertel mit höheren Einkommen haben mehr Baümedensität.
H2.1 - Viertel mit nicht-weissen/(Latino- Afroam?) Ethnien haben weniger Baümedensität.

```{r multireg1}

requiredh11<-c( "ZCTA", "mean_income", "eth_white_nonhisp", "eth_afroam_nonhisp", "eth_asian_nonhisp", "eth_hisp", "eth_other", "pop_density", "tree_density")


df_h11<-na.omit(baumnyc_gp[,requiredh11])
df_h11$income_category<-ifelse(df_h11$mean_income<=quantile(df_h11$mean_income, 0.25), 1, 
                               ifelse(df_h11$mean_income<=quantile(df_h11$mean_income, 0.5), 2,
                                      ifelse(df_h11$mean_income<=quantile(df_h11$mean_income, 0.75), 3, 4)))
#df_h11_log<-log(df_h11[-188,])
#df_h11_log<-df_h11_log[-39,]
#index(df_h11$ZCTA == 11005,)

regh11<-lm(tree_density~mean_income + eth_afroam_nonhisp + eth_asian_nonhisp + eth_hisp + eth_other + pop_density, df_h11)
summary(regh11)

summary(df_h11$tree_density)

``` 


```{r tests}

#OUTLIERS

ols_plot_resid_stud(regh11) #no values out of bounds
ols_plot_resid_lev(regh11)
ols_plot_cooksd_chart(regh11)

df_h11_no<-df_h11[-168,]
df_h11_no<-df_h11_no[-33,]

#LINEARITY - erfüllt 

plot(regh11)
pairs(df_h11)
raintest(regh11)

#MULTI-COLINEARITY NONE

#HETEROSKEDASTICITY

plot(regh11)

ols_plot_resid_fit(regh11)
ols_test_breusch_pagan(regh11)

#NORMALITY
ols_plot_resid_qq(regh11)
shapiro.test(regh11$residuals)
kurtosis(regh11$residuals)
skewness(regh11$residuals)
agostino.test(regh11$residuals)
anscombe.test(regh11$residuals)
```

#### Exotische Baüme

```{r multireg2}

requiredh12<-c( "ZCTA5CE10", "mean_income", "eth_white_nonhisp", "eth_afroam_nonhisp", "eth_asian_nonhisp", "eth_hisp", "eth_other", "pop_density", "native")


df_h12<-na.omit(baumnyc[,requiredh12])
df_h12$income_category<-ifelse(df_h12$mean_income<=quantile(df_h12$mean_income, 0.25), 1, 
                               ifelse(df_h12$mean_income<=quantile(df_h12$mean_income, 0.5), 2,
                                      ifelse(df_h12$mean_income<=quantile(df_h12$mean_income, 0.75), 3, 4)))
df_h12_log<-log(df_h12[-188,])
df_h12_log<-df_h11_log[-39,]
index(df_h11$ZCTA == 11005,)

regh12<-glm(native~mean_income + eth_afroam_nonhisp + eth_asian_nonhisp + eth_hisp + eth_other + pop_density, df_h12, family="binomial")

plot(regh12)
summary(regh12)

summary(df_h11$tree_density)

``` 

```{r K-means clustering}

install.packages("jsonlite")
library(jsonlite)
library(here)
json_data <- fromJSON(here("Data", "Raw","zbp.json"))
data_frame <- as.data.frame(json_data, stringsAsFactors = FALSE)
write.csv(data_frame, "zbp.csv", row.names = FALSE)

# Load necessary library for "here" function if not already loaded
library(here)

data1 <- read.csv(here("Data", "Raw", "zbp.csv"))
data2 <- read.csv(here("Data", "Refined", "Baumnyc2.csv"))

data2$ESTAB <- NA

for (i in 1:nrow(data2)) {
  
  match_index <- which(data1$zipcode == data2$zipcode[i])
  
  
  if (length(match_index) > 0) {
    data2$ESTAB[i] <- data1$ESTAB[match_index]
  }
}


write.csv(data2, here("Data", "Refined", "Baumnyc2_updated.csv"), row.names = FALSE)

```
